package rca.ac.rw.template.common.enums;

public enum PayslipStatus {
    PENDING, // Generated by manager, awaiting admin approval
    PAID,    // Approved by admin, salary disbursed (conceptually)
    REJECTED // If admin rejects a processed payroll for some reason
}